### ISSUE TITLE
Requiring CMS

### ISSUE THREAD

**Issue by swilsonau** [praxisnetau/silverstripe-moderno-admin#1]
Is there any specific reason why you're requiring silverstripe/cms as a dependency? Looking through the code, it doesn't seem like you're using anything that relies on the cms code. I've tested this on my framework project and everything is fine.

Maybe consider removing this dependency?

**Comment by colintucker** [comment]
Well, since Moderno is a skin for the SilverStripe CMS, I assumed that it may in fact require silverstripe/cms to be installed. It's not using code from it per se, but the CMS is required to actually make use of this skin. Oh, and the config YAML makes reference to some classes from the CMS.

**Comment by swilsonau** [comment]
The framework actually contains the admin/ section. So your module will work fine without requiring the CMS dependency. The YAML won't complain about classes that don't exist.

**Comment by colintucker** [comment]
Hmm, in that case, you have a point. I haven't actually done any framework-only projects, so it didn't really occur to me that folks would want to use it for "admin" only stuff (i.e. without the CMS).  If the YAML still works with the missing classes, then that's fine, I'll adjust the dependencies.  :)

**Comment by swilsonau** [comment]
Thank you!
