### ISSUE TITLE
[Bug] Doesn't support ModelAdmins $menu_icon

### ISSUE THREAD

**Issue by mooror** [praxisnetau/silverstripe-moderno-admin#12]
Here at my work we really love the look of your admin theme. We use it quite a bit, which makes me wonder how we didn't spot this bug earlier. But anyway, we have created custom modelAdmins that include the $menu_icon variable in this form:

```
private static $menu_icon = 'mysite/icons/icon.png';   
```

The default silverstripe theme displays the custom icons perfectly fine but when we use the moderno theme it only displays the default icon. 

Thanks in advance,
Mooror

**Comment by colintucker** [comment]
Thanks @mooror I'll check it out. :)

**Comment by mooror** [comment]
And thank you for creating a great theme to begin with. After all, if you hadn't created it we wouldn't be having this conversation :D

Mooror

**Comment by colintucker** [comment]
OK @mooror, that commit should fix the problem with menu icons.  Now, it will detect whether your ModelAdmin subclass has a $menu_icon, an $awesome_icon, or neither.  With neither it will show a nicer font-awesome version of the "database" icon.  With just $menu_icon, it will show the bitmap, and with $awesome_icon it will show the font-awesome icon (disabling the bitmap icon). 👍

**Comment by mooror** [comment]
I just tested this out and everything works great. Thank you for fixing this. Also I read in your above comment that there is support for an $awesome_icon variable. I have never heard of that variable and was wondering if a) that is native to silverstripe or if you added it and b) how one would go about using it. Do you just use the font awesome class for the icon? For example if i wanted to use the clock icon in the modelAdmin would I use something like this?

```
private static $awesome_icon= 'fa-clock-o '
```

Thanks again,
Mooror

**Comment by colintucker** [comment]
It's in the README @mooror 😛  

That's a custom Moderno thing, and yes you just add the class name for the Font Awesome icon you'd like (with or without `fa-` prefix).  Now, Moderno will detect an `$awesome_icon` and use that over `$menu_icon`.  If an awesome icon is not present, it'll use the menu icon, and if neither are present on ModelAdmin subclasses, it will use `fa-database` by default.

**Comment by mooror** [comment]
Sorry about that, I should have checked the readme. But thank you kindly for answering my questions any way :D

**Comment by colintucker** [comment]
No problems.  Use `$awesome_icon` if you can because it will look, er... awesome.  You can also define it in your app's YAML if you want to override a third-party ModelAdmin instance, e.g.:

``` yaml
ThirdPartyClass:
  awesome_icon: fa-thumbs-up
```

This will replace it's default bitmap `$menu_icon` with `fa-thumbs-up`. 👍
