### ISSUE TITLE
[Feature Request] Add ability to change cms logo and logo url

### ISSUE THREAD

**Issue by mooror** [praxisnetau/silverstripe-moderno-admin#13]
We would really like to use your theme for our client sites but until [this issue](https://github.com/praxisnetau/silverstripe-moderno-admin/issues/12) is fixed we are stuck using the silverstripe-cms-branding admin theme/module. So I thought that while I was here posting the other issue I might as well request that moderno supports the silverstripe-cms-branding module (because right now it doesn't seem to) or that you incorporate similar functionality into your admin theme. 

Thanks in advance,
Mooror

**Comment by colintucker** [comment]
That's a good suggestion as well, I'll also look into this for the next release.  :)

**Comment by mooror** [comment]
Thank you for your consideration. Do you happen to have a rough idea about when we could expect the next release? 

Thanks,
Mooror

P.S. I can certainly understand if a timeline is not available at present. I myself find it hard to give time estimates because of the nature of programming (and bugs).

**Comment by colintucker** [comment]
Hi again @mooror!  Looks like I'm going to take the 2nd route with this, and implement the CMS branding functionality within Moderno.  I took a quick look at the CMS branding module and it's... pretty awful lol 😉, so I'm going to replicate it and push to master as soon as a I can.  I'll probably tag the next release after I push that change, so bear with me.

**Comment by colintucker** [comment]
There we go @mooror - have a play around with the new branding tab under Moderno in settings. 😄

**Comment by mooror** [comment]
Thank you so much for adding this so quickly. I will try out the new settings as soon as I can and post my feedback here. 

Thank you for your hard work,
Mooror

P.S. Sorry about the CMS branding module, I had not looked at its code so I had no idea it was "pretty awful".

**Comment by mooror** [comment]
So I just installed the new version with composer and tested it out and I gotta hand it to you, your version of the CMS branding is very slick. The ui is very nice and fits very well with the rest of the moderno design. Great work. Now I did come across one issue that I thought I would mention and that was to do with the custom loading image (which is an awesome feature btw). When I uploaded [this test gif](http://bert.art.yale.edu/~yotamhadar/loading/Loading-3.gif) to try out the new setting. Nothing seemed to change when I would move between cms pages, the default loader still showed up. So I flushed the cache and initiated a dev/build to see if that would remedy the issue. This did indeed change something, as I spotted the custom loader when I traveled from my dev/build url back to the cms (admin/) back-end. But the custom icon was showing up above the default loader (instead of replacing it) and when I moved around inside the cms it was still displaying the default loader. I will try to get a screenshot of what I'm experiencing to clear up and misunderstanding. 

Your work is appreciated,
Mooror

**Comment by mooror** [comment]
Below are two screenchots I took. The first is my moderno loader settings. The second was a bit harder to get (because of how quickly the loader screen disappears) but with a couple tries I was able to get the loader page with both loaders.
[Moderno loader settings](https://snag.gy/2bfaqN.jpg)
[Custom loader above default loader](https://snag.gy/JSOwzD.jpg)

Keep up the great work,
Mooror

**Comment by colintucker** [comment]
Ahh I see, no what Moderno (and likewise the CMS branding module) is doing is allowing you to customise the logo that appears on the loading screen, not the spinner.  However, I could add customisation of the spinner for a future release perhaps.  ;)

**Comment by mooror** [comment]
Oh okay, that makes sense. I apologize for the misunderstanding. I myself have not used the CMS branding module. A colleague of mine used it quite often, and therefor was having trouble moving over to moderno. That's why I requested similar features be added. Hopefully that helps explain my apparent lack of understanding for the "Loading Image" setting :D

Now that I know what the intended functionality of that setting is I realize that it works as expected. Very good work 

Mooror

**Comment by colintucker** [comment]
Thanks!  Customising the spinner is a good idea though too, I'll keep that in mind. ;)
