### ISSUE TITLE
CMS_DIR Constant when no CMS ;)

### ISSUE THREAD

**Issue by mspacemedia** [praxisnetau/silverstripe-moderno-admin#14]
When adding Moderno to a framework only site/app SiteConfigEditFormExtension results in:

[Notice] Use of undefined constant CMS_DIR - assumed 'CMS_DIR'

``` php
        if (defined('CMS_DIR')) {
            Requirements::javascript(CMS_DIR . '/javascript/CMSMain.EditForm.js');
        }
```

Fixes this.

**Comment by colintucker** [comment]
Dang it all... will fix.  :P

**Comment by mspacemedia** [comment]
No problem,  Thank you for moderno btw and will you be bootstrapping it for 4.0.0???

**Comment by colintucker** [comment]
Might be... I need to find some time to play around with the SS4 alpha first.
