### ISSUE TITLE
[Bug][Low Priority] No close icon shown on notifies

### ISSUE THREAD

**Issue by mooror** [praxisnetau/silverstripe-moderno-admin#15]
As far as I'm aware the default silverstripe CMS theme has little X icons on the notifies so that you can close them easily. In the moderno theme those icons don't show up for me. It seems that the icon tag is still there, as when I hover over the top right corner of the notifies the pointer turns into a hand, but unfortunately the icons themselves don't show up. 

[Screenshot](https://snag.gy/QhV6IN.jpg)

Thanks in advance,
Mooror

**Comment by colintucker** [comment]
Hmm, looks like you're right... I thought that SS had removed them, actually, but I can see it's still in the markup but not being shown in Moderno.  It should be replaced by a font-awesome close icon.  Might be a small CSS incompatibility between SS releases.  I'll investigate.  😃

**Comment by mooror** [comment]
I forked this repository, updated the css color for the icon and created a pull request. Please note this only changes the color of the icon so its visible. I didn't know how to replace the icon with a font awesome one :D

**Comment by colintucker** [comment]
Fixed by #17
