### ISSUE TITLE
Missing icons from gridfield

### ISSUE THREAD

**Issue by MarcioBarrientos** [praxisnetau/silverstripe-moderno-admin#2]
Some default icons are missing from the griedfield because they are hidden by the custom css in this module.

![captura de pantalla 2015-09-24 a las 2 52 33 p m](https://cloud.githubusercontent.com/assets/4836851/10086558/3f661476-62cc-11e5-8b25-77181445d5bd.png)

**Comment by colintucker** [comment]
Thank you Marcio, I will look into this and apply a fix.
